using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BrakeSystem : MonoBehaviour
{
    public static BrakeSystem instance;
    public LEDController ledController;
    private ILightBehavior standard, frequency, brightness, area;
    public float brakeIntensity = 0f; // ë¸Œë ˆì´í¬ ê°•ë„ ê°’ (0~1)

    [Header("Properties")] public float frequencyValue;
    private void Awake()
    {
        if (instance == null) instance = this;
    }
    void Update()
    {
        /*// í‚¤ë³´ë“œ ì…ë ¥ìœ¼ë¡œ ë¸Œë ˆì´í¬ ê°•ë„ ì¡°ì ˆ (0~1 ë²”ìœ„ ìœ ì§€)
        if (Input.GetKey(KeyCode.UpArrow) || Input.GetKey(KeyCode.W))
        {
            brakeIntensity += Time.deltaTime;
        }

        if (Input.GetKey(KeyCode.DownArrow) || Input.GetKey(KeyCode.S))
        {
            brakeIntensity -= Time.deltaTime;
        }

        brakeIntensity = Mathf.Clamp(brakeIntensity, 0f, 1f); // ğŸš— 0~1 ë²”ìœ„ë¡œ ì œí•œ*/
    }
}

public enum BrakeType
{
    standard,
    frequency,
    brightness,
    area
}